#
# e4s include for ecp-x86_64 deployment (prod)
#
config:
  install_tree: /ecp/sw/opt/v2.0/x86_64
  module_roots:
    lmod: /ecp/sw/ecp-x86_64/modulefiles/v2/e4s
  build_stage:
  - /var/tmp/$user/spack-stage
  - $spack/var/spack/stage
  verify_ssl: true
  checksum: true
  dirty: false
  source_cache: /ecp/sw/var/spack/cache
  misc_cache: /ecp/sw/var/spack/mcache
  install_missing_compilers: true