#
# conf-general for xx-fe1 deployment (dev)
#
config:
  install_tree: /ecp/sw/opt/v2.0/x86_64
  module_roots:
    lmod:   /ecp/sw/dev/xx-fe1/modulefiles/nmc
  build_stage:
    - /var/tmp/$user/spack-stage
    - $spack/var/spack/stage
  verify_ssl: true
  checksum: true
  dirty: false
  source_cache: /ecp/sw/var/spack/cache
  misc_cache:  /ecp/sw/var/spack/mcache
  install_missing_compilers: true
